/**
 * @description       : 
 * @author            : Maral Begli
 * @group             : 
 * @last modified on  : 07-21-2022
 * @last modified by  : Maral Begli
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   07-21-2022   Maral Begli   Initial Version
**/
public  class Employee_Info {
    public static string EmployeeName ;
        public  void EmployeeDetails(){
        system.debug('employee name is ' + EmployeeName);

    }
}
