/**
 * @description       : 
 * @author            : Maral Begli
 * @group             : 
 * @last modified on  : 07-15-2022
 * @last modified by  : Maral Begli
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   07-15-2022   Maral Begli   Initial Version
**/
public  class Arthimaticcalculations {
    public void addition(integer x,integer y){
        
        System.debug(x+y);

    }
    public void subtraction(integer x,integer y){
        
        System.debug(x-y);

    }
    public void multiplication(integer x,integer y){
        
        System.debug(x*y);
    }    

   

}
