/**
 * @description       : 
 * @author            : Maral Begli
 * @group             : 
 * @last modified on  : 07-14-2022
 * @last modified by  : Maral Begli
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   07-14-2022   Maral Begli   Initial Version
**/
public class calculator {
    public void printNewMessage(string msg){
        //string msg1='something';
       System.debug(msg); 
    }
    
    public void add(integer a, integer b){
        integer sum = a+b;
        system.debug(sum);


    }
}
