/**
 * @description       : 
 * @author            : Maral Begli
 * @group             : 
 * @last modified on  : 07-11-2022
 * @last modified by  : Maral Begli
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   07-11-2022   Maral Begli   Initial Version
**/
public  class CheckDataTypes {
   public void MethodBoolean(){
    boolean checkBoolean= True;
    system.debug(checkBoolean);
   }

   public void MethodInteger(){
    integer varfirst = 1;
    integer varsecond = 2;
    system.debug(varfirst);
    system.debug(varsecond);
   }
   public void StringMethod(){
    string Varname='Name';
    string Var2name='Maral';
    system.debug(Varname);
    system.debug(Var2name);


   }
}
