/**
 * @description       : 
 * @author            : Maral Begli
 * @group             : 
 * @last modified on  : 07-12-2022
 * @last modified by  : Maral Begli
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   07-12-2022   Maral Begli   Initial Version
**/
public class  Primitivedata_Asssignment {
    public void typeid(){
        string  id= '0018Z00002f7sWnQAI';
        string obj1= ' the following Id belongs to Accouts';
        boolean obj2= true;
         system.debug('it is= ' +id+obj1+' and that is '+ obj2 );

        
    }
}




