/**
 * @description       : 
 * @author            : Maral Begli
 * @group             : 
 * @last modified on  : 07-11-2022
 * @last modified by  : Maral Begli
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   07-11-2022   Maral Begli   Initial Version
**/
public  class PtimitiveDataTypeDemo2 {
   public void Print1(){
    Id id1='0018Z00002f7sWmQAI';
    system.debug('print id1= ' + id1);
    Object obj1='This is string';
    Object obj2=15;
    Object obj3='0018Z00002f7sWwQAI';
    Object obj4='True';

    system.debug('obj1 = ' + obj1 );
    system.debug('obj2 = ' + obj2 );
    system.debug('obj3 = ' + obj3 );
    system.debug('obj4 = '+ obj4);

   }
}
